import type { ManifestLoadedData, LevelLoadedData, ErrorData, FragBufferedData } from '../types/events';
import { Level } from '../types/level';
import { Events } from '../events';
import BasePlaylistController from './base-playlist-controller';
import ContentSteeringController from './content-steering-controller';
import type Hls from '../hls';
import type { HlsUrlParameters } from '../types/level';
export default class LevelController extends BasePlaylistController {
    private _levels;
    private _firstLevel;
    private _maxAutoLevel;
    private _startLevel?;
    private currentLevel;
    private currentLevelIndex;
    private manualLevelIndex;
    private steering;
    onParsedComplete: Function;
    constructor(hls: Hls, contentSteeringController: ContentSteeringController | null);
    private _registerListeners;
    private _unregisterListeners;
    destroy(): void;
    stopLoad(): void;
    private resetLevels;
    private onManifestLoading;
    protected onManifestLoaded(event: Events.MANIFEST_LOADED, data: ManifestLoadedData): void;
    private isAudioSupported;
    private isVideoSupported;
    private filterAndSortMediaOptions;
    get levels(): Level[] | null;
    get level(): number;
    set level(newLevel: number);
    get manualLevel(): number;
    set manualLevel(newLevel: number);
    get firstLevel(): number;
    set firstLevel(newLevel: number);
    get startLevel(): number;
    set startLevel(newLevel: number);
    get pathwayPriority(): string[] | null;
    set pathwayPriority(pathwayPriority: string[]);
    protected onError(event: Events.ERROR, data: ErrorData): void;
    protected onFragBuffered(event: Events.FRAG_BUFFERED, { frag }: FragBufferedData): void;
    protected onLevelLoaded(event: Events.LEVEL_LOADED, data: LevelLoadedData): void;
    protected loadPlaylist(hlsUrlParameters?: HlsUrlParameters): void;
    get nextLoadLevel(): number;
    set nextLoadLevel(nextLevel: number);
    removeLevel(levelIndex: number): void;
    private onLevelsUpdated;
    checkMaxAutoUpdated(): void;
}
//# sourceMappingURL=level-controller.d.ts.map